uploads = []

[[generated]]
id = "kXw7kC6T3WuggTVK1CBLT"
uri = "file://artifacts/investor-pitch/public/hero.png"
type = "image"
title = "investor hero background"

[[generated]]
id = "y55xWDIGw7j-GcxUl5ti_"
uri = "file://artifacts/doctor-onboarding/public/clinic-hero.png"
type = "image"
title = "doctor onboarding clinic hero"

[[generated]]
id = "V4lB6m6T7n-Hrq0sEOHr_"
uri = "file://artifacts/doctor-onboarding/src/assets/clinic-crowd.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "dMN3TMyAMBYdKaxqSx9zT"
uri = "file://.local/outputs/Asset-Manager.pdf"
type = "pdf"
title = "Asset Manager.pdf"

[[outputs]]
id = "RS8nonJchkaxJy9wlII2T"
uri = "file://.local/outputs/LINESETU.pptx"
type = "slides"
title = "LINESETU.pptx"
