// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/doctor-app/AddWalkin.tsx": () => import("../components/mockups/doctor-app/AddWalkin.tsx"),
  "./components/mockups/doctor-app/Dashboard.tsx": () => import("../components/mockups/doctor-app/Dashboard.tsx"),
  "./components/mockups/doctor-app/Login.tsx": () => import("../components/mockups/doctor-app/Login.tsx"),
  "./components/mockups/doctor-app/MasterQueue.tsx": () => import("../components/mockups/doctor-app/MasterQueue.tsx"),
  "./components/mockups/doctor-app/Settings.tsx": () => import("../components/mockups/doctor-app/Settings.tsx"),
  "./components/mockups/admin-panel/BookingMonitor.tsx": () => import("../components/mockups/admin-panel/BookingMonitor.tsx"),
  "./components/mockups/admin-panel/Clinics.tsx": () => import("../components/mockups/admin-panel/Clinics.tsx"),
  "./components/mockups/admin-panel/Dashboard.tsx": () => import("../components/mockups/admin-panel/Dashboard.tsx"),
  "./components/mockups/admin-panel/Doctors.tsx": () => import("../components/mockups/admin-panel/Doctors.tsx"),
  "./components/mockups/admin-panel/Revenue.tsx": () => import("../components/mockups/admin-panel/Revenue.tsx"),
  "./components/mockups/admin-panel/Transactions.tsx": () => import("../components/mockups/admin-panel/Transactions.tsx"),
  "./components/mockups/linesetu-design-system/Showcase.tsx": () => import("../components/mockups/linesetu-design-system/Showcase.tsx"),
  "./components/mockups/patient-app/Booking.tsx": () => import("../components/mockups/patient-app/Booking.tsx"),
  "./components/mockups/patient-app/DoctorDetail.tsx": () => import("../components/mockups/patient-app/DoctorDetail.tsx"),
  "./components/mockups/patient-app/Home.tsx": () => import("../components/mockups/patient-app/Home.tsx"),
  "./components/mockups/patient-app/LiveQueue.tsx": () => import("../components/mockups/patient-app/LiveQueue.tsx"),
  "./components/mockups/patient-app/Login.tsx": () => import("../components/mockups/patient-app/Login.tsx"),
  "./components/mockups/patient-app/MyBookings.tsx": () => import("../components/mockups/patient-app/MyBookings.tsx"),
  "./components/mockups/patient-app/Payment.tsx": () => import("../components/mockups/patient-app/Payment.tsx"),
  "./components/mockups/patient-app/Profile.tsx": () => import("../components/mockups/patient-app/Profile.tsx")
};
